<?php
/**
 * Created by PhpStorm.
 * User: Cyn4uk
 * Date: 31.07.2018
 * Time: 23:28
 */

namespace frontend\controllers;
use common\models\Product;
use frontend\models\Cart;
use Yii;

class CartController extends AppController
{

    public function actionAdd()
    {
        $id = Yii::$app->request->get('id');
        debug($id);

        return parent::actions(); // TODO: Change the autogenerated stub
    }
}